version: "3.8"

services:
  laravel:
    image: docker.io/bitnami/laravel:10
    ports:
      - "8000:8000"
    volumes:
      - "./laravel:/app"
    depends_on:
      - mariadb

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./react:/app"
      - "/app/node_modules"

  mariadb:
    image: 'bitnami/mariadb:11.2'
    environment:
      - MARIADB_ROOT_PASSWORD=rootpwd
      - MARIADB_DATABASE=customAIze
      - MARIADB_USER=user
      - MARIADB_PASSWORD=userpwd
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8003:8003"
    volumes:
      - ./fastapi/app:/app

volumes:
  mariadb_data:
    driver: local
