version: "3.8"

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8003:8003"
    volumes:
      - ./fastapi/app:/app
