version: ""

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  laravel:
    image: docker.io/bitnami/laravel:10
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - "./laravel:/app"
    depends_on:
      - mariadb
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - "./react:/app"
      - "/app/node_modules"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8002:8002"
    links:
      - 'mariadb:db'
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - "./fastapi:/app"
    depends_on:
      - mariadb
